### ISSUE TITLE
Allow custom title for replaced tweet

### ISSUE THREAD

**Issue by oxguin** [ciderpunx/userscripts#13]
E.g. "this tweet as bullshit" or "I deleted this tweet"
Referenced to #12

**Comment by oxguin** [comment]
As an interim, coming up with an array along lines of
```
var bsStrings = [
	  "This tweet was bullshit."
	, "Begone twat."
	, "Tweet removed by taste police."
	, "Yuck. Horrible twat removed."
	, "A twat on your TL! Moving on ..."
	, "Look over there *points*. *replaces tweet*."
	, "Yikes! That tweet was awful."
	, "No need to see that tweet."
	, "This was not the tweet you were looking for."
	, "No, no, no."
];
```
And will rand pick one

**Comment by ciderpunx** [comment]
Can the indentation line up the opening [ with the commas and the closing ] I think it looks nice and tidy that way ...

**Comment by ciderpunx** [comment]
I like the random ones here, thing its actually better than being able to customize it, what do you reckon to just leaving it as randomly selected?

**Comment by oxguin** [comment]
Yep, happy to leave it as it is
