### ISSUE TITLE
Have different coloured avis that are randomly selected

### ISSUE THREAD

**Issue by oxguin** [ciderpunx/userscripts#16]

**Comment by ciderpunx** [comment]
I don't like this feature - I think it should be optional. I think it is better to have it be consistent so you can see what is going on...

**Comment by ciderpunx** [comment]
Actually its not so bad after you get used to it. I'll put a config setting in so that you can switch it off if you're a grumpy monochrome lover like me.

**Comment by ciderpunx** [comment]
And default to being switched on
