### ISSUE TITLE
Indentation of blahblahblah text underneath tweet replacements is wonky

### ISSUE THREAD

**Issue by ciderpunx** [ciderpunx/userscripts#20]
It'd be nice if it was always the same (though I prefer it without the blahblahblah text)

![http://i.imgur.com/p3GIJx7.png](http://i.imgur.com/p3GIJx7.png)

**Comment by oxguin** [comment]
I can look at it if we decide to keep it.
TBH, not really feeling like any of my code contributions to TGB are wanted. Tried to call, but guess you're out having fun!

**Comment by ciderpunx** [comment]
Sorry if it came across that way!

**Comment by oxguin** [comment]
I know that really.
Soz, was having a bad day and being over sensitive.
I'm not sure the whether the test is a good thing or not, and not precious about keep it. Though, if we do, I do like the TM bit ;)

**Comment by ciderpunx** [comment]
Let's leave it in. +1 tm. Corporate identity and all that ;-)
